// <auto-generated />
using System;
using GestionDocumental.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GestionDocumental.Migrations
{
    [DbContext(typeof(GestionDocumentalContext))]
    partial class GestionDocumentalContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GestionDocumental.Dominio.DocumentoFormato", b =>
                {
                    b.Property<int>("DocFormatoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DocFormatoId"));

                    b.Property<string>("CodigoDocFormato")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CodigoDocSolicitado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CodigoFormato")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DocumentoSolicitadoDocSolicitadoId")
                        .HasColumnType("integer");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FormatoEntregaFormatoId")
                        .HasColumnType("integer");

                    b.HasKey("DocFormatoId");

                    b.HasIndex("FormatoEntregaFormatoId");

                    b.ToTable("DocumentoFormato");
                });

            modelBuilder.Entity("GestionDocumental.Dominio.DocumentoMedio", b =>
                {
                    b.Property<int>("DocMedioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DocMedioId"));

                    b.Property<string>("CodigoDocMedio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CodigoDocSolicitado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CodigoMedio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DocumentoSolicitadoDocSolicitadoId")
                        .HasColumnType("integer");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MedioEnvioMedioId")
                        .HasColumnType("integer");

                    b.HasKey("DocMedioId");

                    b.HasIndex("MedioEnvioMedioId");

                    b.ToTable("DocumentoMedio");
                });

            modelBuilder.Entity("GestionDocumental.Dominio.DocumentoSolicitado", b =>
                {
                    b.Property<int>("DocSolicitadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DocSolicitadoId"));

                    b.Property<string>("ArchivoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CodigoDocSolicitado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CodigoSolicitud")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CodigoTipoDoc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SolicitudId")
                        .HasColumnType("integer");

                    b.Property<int>("TipoDocumentoTipoDocId")
                        .HasColumnType("integer");

                    b.HasKey("DocSolicitadoId");

                    b.HasIndex("TipoDocumentoTipoDocId");

                    b.ToTable("DocumentoSolicitado");
                });

            modelBuilder.Entity("GestionDocumental.Dominio.EntregaDocumento", b =>
                {
                    b.Property<int>("EntregaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EntregaId"));

                    b.Property<string>("CodigoEntrega")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CodigoFormato")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CodigoMedio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CodigoSolicitud")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CodigoTipoDoc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaEntrega")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FormatoEntregaFormatoId")
                        .HasColumnType("integer");

                    b.Property<int>("MedioEnvioMedioId")
                        .HasColumnType("integer");

                    b.Property<int>("SolicitudId")
                        .HasColumnType("integer");

                    b.Property<int>("TipoDocumentoTipoDocId")
                        .HasColumnType("integer");

                    b.HasKey("EntregaId");

                    b.HasIndex("FormatoEntregaFormatoId");

                    b.HasIndex("MedioEnvioMedioId");

                    b.HasIndex("TipoDocumentoTipoDocId");

                    b.ToTable("EntregaDocumento");
                });

            modelBuilder.Entity("GestionDocumental.Dominio.FormatoEntrega", b =>
                {
                    b.Property<int>("FormatoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FormatoId"));

                    b.Property<string>("CodigoFormato")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NombreFormato")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("FormatoId");

                    b.ToTable("FormatoEntrega");
                });

            modelBuilder.Entity("GestionDocumental.Dominio.MedicoDoc", b =>
                {
                    b.Property<int>("MedicoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MedicoId"));

                    b.Property<string>("CodigoMedico")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NombreMedico")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MedicoId");

                    b.ToTable("MedicoDoc");
                });

            modelBuilder.Entity("GestionDocumental.Dominio.MedioEnvio", b =>
                {
                    b.Property<int>("MedioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MedioId"));

                    b.Property<string>("CodigoMedio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NombreMedio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MedioId");

                    b.ToTable("MedioEnvio");
                });

            modelBuilder.Entity("GestionDocumental.Dominio.PacienteDoc", b =>
                {
                    b.Property<int>("PacienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PacienteId"));

                    b.Property<string>("CodigoPaciente")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NombrePaciente")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PacienteId");

                    b.ToTable("PacienteDoc");
                });

            modelBuilder.Entity("GestionDocumental.Dominio.SolicitudDocumentacion", b =>
                {
                    b.Property<int>("SolicitudId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SolicitudId"));

                    b.Property<string>("CodigoMedico")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CodigoPaciente")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CodigoSolicitud")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DepartamentoSolicitante")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("MedicoDocMedicoId")
                        .HasColumnType("integer");

                    b.Property<int?>("PacienteDocPacienteId")
                        .HasColumnType("integer");

                    b.HasKey("SolicitudId");

                    b.HasIndex("MedicoDocMedicoId");

                    b.HasIndex("PacienteDocPacienteId");

                    b.ToTable("SolicitudDocumentacion");
                });

            modelBuilder.Entity("GestionDocumental.Dominio.TipoDocumento", b =>
                {
                    b.Property<int>("TipoDocId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TipoDocId"));

                    b.Property<string>("CodigoTipoDoc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DepartamentoOrigen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NombreDocumento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TipoDocId");

                    b.ToTable("TipoDocumento");
                });

            modelBuilder.Entity("GestionDocumental.Dominio.DocumentoFormato", b =>
                {
                    b.HasOne("GestionDocumental.Dominio.FormatoEntrega", null)
                        .WithMany("DocumentosFormato")
                        .HasForeignKey("FormatoEntregaFormatoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GestionDocumental.Dominio.DocumentoMedio", b =>
                {
                    b.HasOne("GestionDocumental.Dominio.MedioEnvio", null)
                        .WithMany("DocumentosMedio")
                        .HasForeignKey("MedioEnvioMedioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GestionDocumental.Dominio.DocumentoSolicitado", b =>
                {
                    b.HasOne("GestionDocumental.Dominio.TipoDocumento", null)
                        .WithMany("DocumentosSolicitados")
                        .HasForeignKey("TipoDocumentoTipoDocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GestionDocumental.Dominio.EntregaDocumento", b =>
                {
                    b.HasOne("GestionDocumental.Dominio.FormatoEntrega", null)
                        .WithMany("Entregas")
                        .HasForeignKey("FormatoEntregaFormatoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionDocumental.Dominio.MedioEnvio", null)
                        .WithMany("Entregas")
                        .HasForeignKey("MedioEnvioMedioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionDocumental.Dominio.TipoDocumento", null)
                        .WithMany("Entregas")
                        .HasForeignKey("TipoDocumentoTipoDocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GestionDocumental.Dominio.SolicitudDocumentacion", b =>
                {
                    b.HasOne("GestionDocumental.Dominio.MedicoDoc", null)
                        .WithMany("Solicitudes")
                        .HasForeignKey("MedicoDocMedicoId");

                    b.HasOne("GestionDocumental.Dominio.PacienteDoc", null)
                        .WithMany("Solicitudes")
                        .HasForeignKey("PacienteDocPacienteId");
                });

            modelBuilder.Entity("GestionDocumental.Dominio.FormatoEntrega", b =>
                {
                    b.Navigation("DocumentosFormato");

                    b.Navigation("Entregas");
                });

            modelBuilder.Entity("GestionDocumental.Dominio.MedicoDoc", b =>
                {
                    b.Navigation("Solicitudes");
                });

            modelBuilder.Entity("GestionDocumental.Dominio.MedioEnvio", b =>
                {
                    b.Navigation("DocumentosMedio");

                    b.Navigation("Entregas");
                });

            modelBuilder.Entity("GestionDocumental.Dominio.PacienteDoc", b =>
                {
                    b.Navigation("Solicitudes");
                });

            modelBuilder.Entity("GestionDocumental.Dominio.TipoDocumento", b =>
                {
                    b.Navigation("DocumentosSolicitados");

                    b.Navigation("Entregas");
                });
#pragma warning restore 612, 618
        }
    }
}
